### ISSUE TITLE
idea vimでモードを表示したい。

### ISSUE THREAD

**Issue by momoe-VG-zz** [momoe-VG/dotfiles#3]
insert modeなのかnormal modeなのかわかんないのつらいってわっさんに言われた。
そういえばあんま気になってはいなかったけどたまに間違えるので表示がほしい。

**Comment by nishigori** [comment]
[Bug tracker](http://youtrack.jetbrains.com/issues/VIM) みる限り今はまだないみたいだねぇ

**Comment by momoe-VG-zz** [comment]
みたいですねぇ〜。
カーソルが変わるから感覚的にわかるし、すごく困ってるわけではないのでいいかな。
